### ISSUE TITLE
Post Installation Errors

### ISSUE THREAD

**Issue by hcatlin** [ParamagicDev/snowpacker#26]
On an existing project, I attempted to follow the installation instructions, and everything was fine until my first attempt at starting the dev server:

```
[snowpack] [Snowpack 2.11.0] `buildOptions.minify` has moved to package "@snowpack/plugin-optimize". Install it and include as a plugin in your Snowpack config file.

See https://www.snowpack.dev/#configuration for more info.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rails aborted!
Command failed with status (1): [NODE_ENV=development yarn run snowpack dev...]
/Users/hcatlin/.rvm/gems/ruby-2.7.2/bundler/gems/snowpacker-96eb376f9726/lib/snowpacker/runner.rb:40:in `snowpacker_command'
/Users/hcatlin/.rvm/gems/ruby-2.7.2/bundler/gems/snowpacker-96eb376f9726/lib/snowpacker/runner.rb:32:in `dev'
```

**Comment by hcatlin** [comment]
I then noticed there was a yarn command, so tried to run `NODE_ENV=development yarn run snowpack dev` which resulted in: 

```
snowpack

▼ Console

[snowpack] File size (31551019513) is greater than 2 GB

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ParamagicDev** [comment]
Yea this repo needs some love. This was create back around Snowpack `v2.7.1` I believe and were now on `v2.17.1` and the `rc`for `v3.0.0` just dropped. Definitely need to look into whats going on here, but this needs updates in general.

**Comment by ParamagicDev** [comment]
I also just pushed up 80 commits I had laying around on my development branch to allow users to play around with this a little more. Its possible this *may* solve these issues
